### ISSUE TITLE
UITableViewController

### ISSUE THREAD

**Issue by hobbesthetige** [antoniocasero/Panels#1]
Hi, this doesn't work on when presenting from a UITableViewController :(

**Comment by antoniocasero** [comment]
Hi 👋 
Could you be more specific? What is not working?

**Comment by hobbesthetige** [comment]
It looks like the constraints don't work against the tableview in a UITableViewController subclass. I was able to work around by changing my controller to a UIViewController and adding a tableview to it.

![2018-10-05 13 32 30](https://user-images.githubusercontent.com/4026614/46550481-35a48900-c8a3-11e8-93ab-962a91fcde0a.gif)

**Comment by antoniocasero** [comment]
Yep, UITableViewController contains a tableView instead of a view. The table view is a scrollview and its contents are dynamic, so the layout works differently. I'm afraid there is no way to work around these things.
