### ISSUE TITLE
2nd time dismiss animation works but panel stay

### ISSUE THREAD

**Issue by deshan** [antoniocasero/Panels#14]
Panel
1. Show
2. Dismiss
3. Show
4. Dismiss (Here after dismiss animation, panel stay remain on visible position )

Any help?

Below is my code, took latest from pods (2.0.3)
```
            if self.currentPanel != nil {
                panelManager?.dismiss()
                self.currentPanel = nil
            } else {
                currentPanel = UIStoryboard.instantiatePanel(identifier: "PanelOptions")
                var panelConfiguration = PanelConfiguration(size: .custom(200))
                panelConfiguration.panelVisibleArea = 30
                
                panelManager?.show(panel: currentPanel as! UIViewController & Panelable, config: panelConfiguration)
            }
```

**Comment by antoniocasero** [comment]
Hi @deshan, I'm going to need more information:

- This panel performs dismiss operation but it appears again? or a new panel comes up?
- Where the code above is executed? After pressing a button?
- Could you check if the panel `deinit` method is called when the panel is dismissed?

**Comment by deshan** [comment]
Sorry for the late reply.
1. Yes I am creating a new panel. but dismiss animation shows, but prev panel stays
2. Yes after button press
3. deinit not get called. Memory grows.

Thank you and again many apologies!

**Comment by deshan** [comment]
I think found the issue.

This would be needed. 
```
self.panel?.removeFromParentViewController()
self.panel?.view.removeFromSuperview()
```

Ofc it's been called in 
`self.panel?.removeContainer()`
But the second time it doesn't get called the reason is self.panel is nil

self.panel = nil moving inside the closure may fix the issue? haven't tried. I manually called them inside my code.
```
UIView.animate(withDuration: configuration.dismissAnimationDuration, animations: {
            panelView.frame.origin = CGPoint(x: 0, y: self.containerView!.frame.size.height)
        }) { _ in
            self.panel?.removeContainer()
            completion?()
            self.panel = nil // moving here may fix the issue
        }
```

**Comment by antoniocasero** [comment]
@deshan  I have a question you said 

> Yes I am creating a new panel. but dismiss animation shows, but prev panel stays

how many panels are you presenting? If you create more than one, then you wouldn't have control over it and it will stay on the screen. You should dismiss the first panel before present the new one.
