### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by moisebc** [antoniocasero/Panels#16]
Hi,

I've tried to put the material panel at the top of view controller but I couldn't. Is there any way to do this?

**Comment by antoniocasero** [comment]
Hi @moisebc, I'm going to need more information about your problem in order to help you...
if you create the panel in the viewDidLoad of the parent, the panel should be on top.

**Comment by moisebc** [comment]
I've just played in your example project (I didn't create a new one in my project). I will try and if I'll have any problem I'll come back.

Thank you very much.

**Comment by antoniocasero** [comment]
I will close this ticket, please reopen if needed
