### ISSUE TITLE
Example app crashes if you tap "Close" twice

### ISSUE THREAD

**Issue by julianschiavo** [antoniocasero/Panels#3]
The example app crashes while unwrapping an optional if you open the "Material" example, then open the panel and tap Close a few times. 

`movePanel(value:keyboard:completion:)`

    panelHeightConstraint!.constant = value
    Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by antoniocasero** [comment]
Thank you again @justJS

**Comment by julianschiavo** [comment]
No problem 👍
