### ISSUE TITLE
Show the Panels on top of a TabBar

### ISSUE THREAD

**Issue by matiaz** [antoniocasero/Panels#5]
Is it possible to show/present a panel from a view controller that is in a TabBar? I want to show a Panel and present it on top of the TabBar. Thanks

**Comment by antoniocasero** [comment]
Sure, Panels is only dependent on the view where is added to. If the bottom layout is above to the TabBar, then your panel will appear on top of the TabBar. If the view is behind the TabBar, then you could use the property `panelMargin` to place panels properly on top of it.

**Comment by matiaz** [comment]
Interesting, I'll to do that. thanks
