### ISSUE TITLE
HeaderHeight calculation pushes Header further down with each show

### ISSUE THREAD

**Issue by caffeineflo** [antoniocasero/Panels#7]
The premise is relatively simple, looking at https://github.com/antoniocasero/Panels/blob/master/Sources/Panels.swift#L50 the safeAreaBottom is added to the PanelHeightConstraint every time show is being executed.

Now in my specific use case, I instantiate the Panelable VC with my parent VC and only show the Panel on didSelect, I dismiss it on didDeselect. With this behavior, the headerHeigh grows every time I execute `show` which ends up pushing my header further down each time.
The examples show the same behavior (although, it's constraints break and recovery recovers the correct constraints).

**Comment by antoniocasero** [comment]
Yes, this is a use case that I didn't contemplate. It happens when the panel is reused to be shown/dismissed. I have a solution in mind,  I will push a fix this weekend. 
Thanks for reporting 👍

**Comment by antoniocasero** [comment]
Please @caffeineflo, reopen if you still have problems

**Comment by caffeineflo** [comment]
I'll try it tomorrow morning and report back. Thanks for the quick turnaround!

**Comment by caffeineflo** [comment]
@antoniocasero I might be missing some configuration to make this work.
But when I click the panel now, it won't scroll up... I'll add a gif to it that makes it more clear

**Comment by antoniocasero** [comment]
Some example code would be perfect

**Comment by caffeineflo** [comment]
I instantiate the panel with the VC, so e.g. `let panel = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "Panel") as! PanelClass` (PanelClass conforms to Panelable). Now on `didSelect` I show the panel and on `didDescelect` I dismiss the panel.
See gif for the behavior this ends up giving me
![panels](https://user-images.githubusercontent.com/1525283/47797388-85516580-dd26-11e8-8fdd-674f93380ac1.gif)

**Comment by antoniocasero** [comment]
Sorry I can not reproduce this issue. Maybe some missing values in the PanelConfiguration?
Could you check what is the `value` in the method -movePanel(_:) when you tap on the panel?
